services:
  postgres:
    image: postgres:17.1-alpine
    container_name: peliculas
    restart: unless-stopped
    environment:
      POSTGRES_DB: peliculas
      POSTGRES_PASSWORD: 1020july
      POSTGRES_USER: postgres-peliculas
    ports:
      - "55433:5432"
    volumes:
      - peliculas_pgdata:/var/lib/postgresql/data

volumes:
  peliculas_pgdata: