#application.properties
spring.profiles.active=dev


spring.datasource.driver-class-name=org.postgresql.Driver
spring.application.name=PeliculasEjercicioSpringBoot
server.servlet.context-path=/peliculas-juli/api


#LangChain4J

langchain4j.open-ai.chat-model.model-name=gpt-4o-mini
