INSERT INTO peliculas (titulo, duracion, genero, fecha_estreno, clasificacion, estado) VALUES ('El Origen', 148,
                                                                                               'Ciencia Ficcion',
                                                                                               '2010-07-16', 8.80, 'A'),
                                                                                              ('Titanic', 195,
                                                                                               'Romance', '1997-12-19',
                                                                                               7.90, 'A'),
                                                                                              ('Gladiador', 155,
                                                                                               'Accion', '2000-05-05',
                                                                                               8.50, 'A'),
                                                                                              ('Interestelar', 169,
                                                                                               'Ciencia Ficcion',
                                                                                               '2014-11-07', 8.60, 'A'),
                                                                                              ('Matrix', 136,
                                                                                               'Ciencia Ficcion',
                                                                                               '1999-03-31', 8.70, 'A'),
                                                                                              ('Forrest Gump', 142,
                                                                                               'Drama', '1994-07-06',
                                                                                               8.80, 'A'),
                                                                                              ('El Padrino', 175,
                                                                                               'Drama', '1972-03-24',
                                                                                               9.20, 'A'),
                                                                                              ('Batman El Caballero Oscuro',
                                                                                               152, 'Accion',
                                                                                               '2008-07-18', 9.00, 'A'),
                                                                                              ('Parasitos', 132,
                                                                                               'Thriller', '2019-05-30',
                                                                                               8.60, 'A'),
                                                                                              ('Joker', 122, 'Drama',
                                                                                               '2019-10-04', 8.40, 'A'),
                                                                                              ('Avengers Endgame', 181,
                                                                                               'Accion', '2019-04-26',
                                                                                               8.40, 'A'),
                                                                                              ('La La Land', 128,
                                                                                               'Musical', '2016-12-09',
                                                                                               8.00, 'A'),
                                                                                              ('Whiplash', 107, 'Drama',
                                                                                               '2014-10-10', 8.50, 'A'),
                                                                                              ('Coco', 105, 'Animacion',
                                                                                               '2017-11-22', 8.40, 'A'),
                                                                                              ('Toy Story', 81,
                                                                                               'Animacion',
                                                                                               '1995-11-22', 8.30, 'A'),
                                                                                              ('El Señor de los Anillos La Comunidad',
                                                                                               178, 'Fantasia',
                                                                                               '2001-12-19', 8.80, 'A'),
                                                                                              ('Harry Potter y la Piedra Filosofal',
                                                                                               152, 'Fantasia',
                                                                                               '2001-11-16', 7.60, 'A'),
                                                                                              ('Jurassic Park', 127,
                                                                                               'Aventura', '1993-06-11',
                                                                                               8.10, 'A'),
                                                                                              ('Mad Max Fury Road', 120,
                                                                                               'Accion', '2015-05-15',
                                                                                               8.10, 'A'),
                                                                                              ('El Viaje de Chihiro', 125, 'Animacion', '2001-07-20', 8.60, 'A')
ON CONFLICT (titulo) DO NOTHING;